version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-session
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: mongodb-agents
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: agent_schemas
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
